### ISSUE TITLE
It doesn't work on version 2020.1

### ISSUE THREAD

**Issue by AprilViolet** [Otanikotani/view-github-actions-idea-plugin#34]
Hello, developer, this plug-in is very good, But It doesn't work on version 2020.1

**Comment by AprilViolet** [comment]
It still does not support 2020.1

**Comment by jason-edstrom** [comment]
@Otanikotani, @tofik-mamishov

**Comment by Otanikotani** [comment]
Taking a look at this, some updated interfaces in JB github plugin and the actions plugin is not compatible. Fixing it.

**Comment by Otanikotani** [comment]
Hopefully fixed in [1.14](https://plugins.jetbrains.com/plugin/13793-github-actions/update/85433 )

**Comment by AprilViolet** [comment]
thanks
