### ISSUE TITLE
Unable to install on Webstorm WS-202.6397.88

### ISSUE THREAD

**Issue by wusatosi** [Otanikotani/view-github-actions-idea-plugin#37]
Hi! I am unable to install GitHub actions plugin on the latest WebStorm.
The error message is: 
`Plugin 'Github Actions' version 1.1.5 is incompatible with this installation: until build 201.SNAPSHOT < WS-202.6397.88`
![image](https://user-images.githubusercontent.com/26424577/89114202-55f7fb80-d4ac-11ea-88ba-7f6111a25e57.png)

I'm using latest release of this plugin (1.1.5) from [jetbrain's plugin site](https://plugins.jetbrains.com/plugin/13793-github-actions).
My WebStorm version (latest):
WebStorm 2020.2
Build #WS-202.6397.88, built on July 25, 2020
Runtime version: 11.0.7+10-b944.20 amd64

**Comment by Otanikotani** [comment]
This takes longer than expected because Idea 2020.2 changed github-related code which was used by the plugin. Work in progress to rewrite the plugin to support the changes

**Comment by Otanikotani** [comment]
Uploaded version 1.1.6 with the IDEA support for builds 202.6397 and onward. It will be available as soon as JetBrains reviews it (usually couple of days)
